from typing import Callable, Dict, List, Union

from zineb.models.datastructure import Model
from zineb.utils.containers import SmartDict

class BaseConstraint:
    name: str = ...
    model: Model = ...
    _data_container: SmartDict = ...
    constrained_fields: List[str] = ...
    condition: Callable = ...
    values: dict = ...
    unique: List = ...
    unique_together: List[List[str], List[str]] = ...
    def __init__(self, fields: List[str], name: str, condition: Callable[..., Union[str, int, float]]=None) -> None: ...
    def __repr__(self) -> str: ...
    def __call__(self, raise_exception: bool = ...) -> List: ...
    def prepare(self, model: Model) -> None: ...
    def check_constraint(self, value_to_check) -> None: ...


class UniqueConstraint(BaseConstraint):
    def check_constraint(self, value_to_check: Union[str, int, float]) -> bool: ...


class CheckConstraint(BaseConstraint):
    def check_constraint(self, value_to_check: Union[str, int, float]) -> Dict: ...
