#!/usr/bin/env python

import os
import sys

from zineb.management import execute_command_inline

if __name__ == '__main__':
    os.environ.setdefault('ZINEB_SPIDER_PROJECT', 'project_name_placeholder')
    execute_command_inline(sys.argv)
