from typing import Any, List, Type, TypeVar, Union

from zineb.http.request import HTTPRequest
from zineb.http.responses import HTMLResponse, JsonResponse, XMLResponse
from zineb.utils.iteration import RequestQueue

# T = TypeVar('T', bound='Spider')

class SpiderOptions:
    domains: list = ...
    limit_requests_to: int = ...
    python_path: str = ...
    prepared_requests: RequestQueue = ...
    spider: Type = ...
    spider_name: str = ...
    start_urls: list = ...
    verbose_name: str = ...
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, name) -> str: ...
    def initialize_queue(self) -> None: ...


class BaseSpider(type):
    def __new__(cls, name: str, bases: tuple, attrs: dict): ...


class Spider(metaclass=BaseSpider):
    meta: SpiderOptions = ...
    start_urls: List[str] = ...
    def __init__(self): ...
    def __repr__(self) -> str: ...
    def __getattribute__(self, name) -> Any: ...
    def _resolve_requests(self) -> None: ...
    def start(self, response: Union[HTMLResponse, JsonResponse, XMLResponse], request: HTTPRequest = None, **kwargs) -> Any: ...


# class SitemapCrawler(Spider): ...


class FileCrawler:
    start_files: List[str] = ...
    root_dir: str = ...
    def __init__(self): ...
