from collections import defaultdict
from zineb.models.datastructure import Model
from typing import Any, Dict, List, Optional, Union

class SmartDict:
    current_updated_fields: set = ...
    order_by: List[List[str, bool]] = ...
    values: defaultdict = ...
    def __init__(self, *fields: str, order_by: Optional[List[List[str, bool]]]): ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @classmethod
    def new_instance(cls, model: Model) -> SmartDict: ...
    def get_container(self, name: str): ...
    def update(self, name: str, value: Union[str, int, float, list, dict]) -> None: ...
    def update_multiple(self, attrs: dict) -> None: ...
    def apply_sort(self, values: List) -> List: ...
    def as_values(self) -> Dict[str, List[str]]: ...
    def as_list(self, include_index: bool=False) -> List[Dict[str, Any]]: ...
    def as_csv(self) -> List[List[Any]]: ...
    def execute_save(self, commit: bool = ..., filename: str = ..., extension: str = ..., **kwargs) -> Union[dict, None]: ...
